### PR TITLE
Upgrade outdated dependencies in the generator

### PR DESCRIPTION
**Pull request by UlisesGascon**
Generator dependencies updated as requested in #759

```
 yeoman-generator         ^3.1.1  →   ^4.0.1 
 @babel/core              ^7.2.2  →   ^7.4.5 
 eslint                  ^5.10.0  →  ^5.16.0 
 eslint-config-prettier   ^3.3.0  →   ^4.3.0 
 eslint-plugin-prettier   ^3.0.0  →   ^3.1.0 
 husky                    ^1.2.1  →   ^2.3.0 
 lint-staged              ^8.1.0  →   ^8.1.7 
 mocha                    ^5.2.0  →   ^6.1.4 
 prettier                ^1.15.3  →  ^1.17.1 
 yeoman-assert            ^3.0.0  →   ^3.1.1 
 yeoman-test              ^1.6.0  →   ^2.0.0 
```

### CODE REVIEW

**Comment by UlisesGascon** [comment]
This error with Node@6 test has been solved in #761 (removed compatibility)

**Review by silvenon — CHANGES_REQUESTED** [review]
`yarn.lock` should also be updated.

**Comment by UlisesGascon** [comment]
`yarn.lock` updated as requested ;-)

**Comment by silvenon** [comment]
Thanks! Just FYI, I deleted `package-lock.json` on master, you added it as a part of this PR, but I didn't want to bother you any further so I deleted it myself.

**Pull request merged**
