### PR TITLE
Time to upgrade dependencies

### LINKED ISSUE #731: Upgrade dependencies
Hi team!

I saw some dependencies outdated...

- Security Risk
    - [x] command-exists (1.2.2 -> 1.2.x)
- Critical
    - [x] yeoman-generator (1.1.1 -> 3.x)
    - [x] generator-jasmine (1.0.0 -> 2.x)
    - [x] chalk (1.0.0 -> 2.x)
    - [x] [devDependencies] mocha (3.1.0 -> 5.x)

I will start the migration in my fork and I will send a PR asap ;-)

**More info**
- [David DM](https://david-dm.org/yeoman/generator-webapp?type=dev)
- [Synk Report](https://snyk.io/test/github/yeoman/generator-webapp?tab=dependencies)

### PR DESCRIPTION
**Pull request by UlisesGascon**
Fix #731

### CODE REVIEW

**Comment by UlisesGascon** [comment]
We need to upgrade the project to Node `>=6`... is that ok for you, @silvenon ?

**Review by silvenon — COMMENTED** [review]
Yes, you can update to Node >= 6. Did you try if the generator works properly with these dependencies updated? You can run `npm link` inside the repository to have it available as if it was installed globally.

**Comment by UlisesGascon** [comment]
Yes, I used npm link to see the changes and validate the generation. But I didn't check the compatibility because I am using only Node v10 in this machine

**Comment by UlisesGascon** [comment]
I will update now the travis configuration in order to avoid v4 and v5. I will include v8 and v10 too

**Comment by silvenon** [comment]
⭐️⭐️⭐️⭐️⭐️

**Pull request merged**
