### PR TITLE
Make it easier to debug errors in .jsx files

### PR DESCRIPTION
**Pull request by zarembas**
It was very hard for me to understand what the error was from the current output (related to [#412](https://github.com/yeoman/generator-gulp-webapp/issues/412)).
Using console.log() will tell you what the error is, the file that triggers it and the exact line number. The gulp server will also not crash every time it outputs an error. Make sure you keep an eye on the console.

### CODE REVIEW

**Comment by silvenon** [comment]
Thanks :smiley: Though I think it might be better to replace gulp-react with gulp-babel, see the [deprecation notice](https://github.com/sindresorhus/gulp-react#deprecated-in-favor-of-gulp-babel-read-more). Perhaps gulp-babel has better error handling.

**Comment by vassyz** [comment]
I thought about that as well, but I've never used gulp-babel. This was a quick fix for my current project.

I also added sourcemaps in my second commit.

**Comment by silvenon** [comment]
Should be the same thing, only better. But the error handling should be checked.

**Comment by addyosmani** [comment]
:+1: for gulp-babel

**Comment by vassyz** [comment]
I replaced gulp-react with gulp-babel, and it's working fine. I removed the error checking, as it seems to be built-in into babel. :smirk:

**Comment by silvenon** [comment]
Awesome! Thanks :+1:

**Pull request merged**
