### PR TITLE
Missing space in index.html

### PR DESCRIPTION
**Pull request by stophecom**

### CODE REVIEW

**Comment by stophecom** [comment]
This is huge!

**Comment by silvenon** [comment]
Thanks! Can the space be before `class` (inside the `if` statement), rather than after `h1`? That way we won't have an extra space if `legacyBootstrap` is `true`.

**Review by neilhem — COMMENTED** [review]
Please add space inside if statement

**Comment by stophecom** [comment]
@neilhem makes sense

**Pull request merged**
