### PR TITLE
Update to yo-gen 0.22 and update tests

### PR DESCRIPTION
**Pull request by eddiemonge**
- Removes entries from gitignore for old style tests
- Update to use yeoman-test
- Update tests to run in os tmp dir instead of test/temp

### CODE REVIEW

**Comment by silvenon** [comment]
I'd like to dump Node 0.x versions, our generator doesn't seem to work on those anyway. #467 

All aboard? @sindresorhus @SBoudrias @addyosmani

**Comment by sindresorhus** [comment]
:+1:

**Comment by SBoudrias** [comment]
:+1: - good update btw, I love all that red!

**Comment by silvenon** [comment]
I was hoping pushing to master will apply to Travis tests for this PR, apparently I need GitHub lessons. Could you cherry pick 3e4526f548f7195658dc771e3e41e94f84458419 or something?

**Comment by eddiemonge** [comment]
changed the one es2015 feature I was using so it should pass in older tests and won't be considered a breaking change

**Pull request merged**
