### PR TITLE
Add build dependency before serving built app

### PR DESCRIPTION
**Pull request by ghost**
Create a fresh, distributable copy of the app before serving

### CODE REVIEW

**Comment by silvenon** [comment]
Thanks for your contribution 👍 I was thinking about this as well, but imagine how frustrating it would be having that task rebuild the app every time. Maybe you want to shut down the server for some reason, then later check again, now you have to rebuild again. If you have a good reason for this that I overlooked, I'm open to convincing.

**Comment by kyleloopback** [comment]
For me personally, I served a dist copy, shut down the server, made some changes, and ran the command again, only to find my changes weren't there. Seems odd to have to explicitly build your app before serving the built copy. I found _that_ frustrating. No worries if you don't add it in to the gen though, easy add on my side.

**Comment by ghost** [comment]
For me personally, I served a dist copy, shut down the server, made some changes, and ran the command again, only to find my changes weren't there. Seems odd to have to explicitly build your app before serving the built copy. I found _that_ frustrating. No worries if you don't add it in to the gen though, easy add on my side.

**Comment by silvenon** [comment]
Hm, you're right. The main reason why you'd want to restart `serve:dist` is probably to check new changes. Could you rebase and resolve conflicts? Then I'll merge it.

**Comment by sindresorhus** [comment]
ping @alwynsays

**Comment by ghost** [comment]
Sorry about the major lag! Rebased and ready to go.

**Comment by silvenon** [comment]
Thanks! I changed it to run `default` instead of `build` to ensure a clean build.

**Pull request merged**
