### PR TITLE
Add note about templating languages

### PR DESCRIPTION
**Pull request by silvenon**
@sindresorhus @arthurvr is this ok? We get a lot of these requests, so I want to make it clear.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Text looks ok, but should probably be a `faq.md` document linked to from the readme.

**Comment by silvenon** [comment]
Good idea.

**Comment by addyosmani** [comment]
Can we update this to an FAQ.md?

**Comment by silvenon** [comment]
Done.

**Pull request merged**
