### PR TITLE
Using Yeoman assertion

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sindresorhus** [comment]
The module should be required separately https://github.com/yeoman/yeoman-assert It's only part of the API for now for legacy reasons.

**Comment by LambertEliott** [comment]
Hello sindre, 

Ok I will do that !

Thanks

**Comment by sindresorhus** [comment]
> Also, please don't open new PRs for every change. Just push new changes to this PR.

**Comment by LambertEliott** [comment]
Yes sorry, I didn't know, it's all new for me.

**Comment by sindresorhus** [comment]
Looks good, thanks :)

**Pull request closed without merging**
