### PR TITLE
Update browserify.md

### PR DESCRIPTION
**Pull request by seb-thomas**
Was errorring with 

```
error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'
```

### CODE REVIEW

**Comment by silvenon** [comment]
Great! Could you please squash your commits into one?

**Comment by seb-thomas** [comment]
@silvenon  
Happy to help! :) 
erm, I think I've squashed that now. Not sure.

**Comment by silvenon** [comment]
@plonko now there are 4 commits, the goal is to have 1 commit (in this case). 😁 Here's [an article](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) on how to do it. After you squash the commits, a force push (`git push -f`) will be necessary. If you need help, let me know. 😉

You can see how many commits there are in a PR by clicking on the "Commits" tab.

**Comment by neilhem** [comment]
@silvenon github's a new feature "Squash & merge" is a time saver.

**Comment by silvenon** [comment]
@neilhem thanks, totally forgot about that. 😅

**Pull request merged**
